### ISSUE TITLE
Slight font and padding changes on topbar in wiki

### ISSUE THREAD

**Issue by untitaker** [remotestorage/website#17]
If you hit "Get Storage" (or any wiki link) from the frontpage, the topbar changes font and padding.

**Comment by skddc** [comment]
What browser? Didn't see that before. You might have to force-reload wiki pages to get the new topbar, if you had them open recently.

**Comment by untitaker** [comment]
Firefox 45. This also seems nonsensical to me as the "computed style" seems to be exactly the same for both sites, as far as I can tell.

**Comment by skddc** [comment]
Zoom level the same? Does one have a scrollbar and the other does not?

**Comment by untitaker** [comment]
Zoom level is 1:1. Unsure what you mean with scrollbar, there is only one scrollbar for the entire pagecontent on the frontpage.

Frontpage:

![2016-04-06-185734_346x96_scrot](https://cloud.githubusercontent.com/assets/837573/14325409/8f131ea0-fc29-11e5-928f-a7aacb062d6f.png)

Wiki:

![2016-04-06-185727_366x75_scrot](https://cloud.githubusercontent.com/assets/837573/14325410/93030048-fc29-11e5-9444-92d37ffab6ad.png)

**Comment by skddc** [comment]
Looks like it's not using Open Sans in the wiki on your machine. I have it installed in my system, so that might be why it works for me. Thanks for reporting, will try to fix it later today!

**Comment by untitaker** [comment]
That's correct, and installing that font fixes it! I have no idea why it would produce an inconsistency between those two pages.

**Comment by skddc** [comment]
Because the webfont from Google is imported correctly on one site, but not on the other. ;)

**Comment by skddc** [comment]
Should be fixed now, but I'm not certain.

**Comment by untitaker** [comment]
I still have this issue, even in private browsing mode :S

**Comment by skddc** [comment]
Could you force-reload and check again? I'm included the `@import` CSS right above the topbar markup now. I can see the font-face rules load from Google Fonts in my Chrome resources panel now.

**Comment by untitaker** [comment]
It works now, thank you!
