### ISSUE TITLE
Automate Let's Encrypt certs on renewals on Discourse

### ISSUE THREAD

**Issue by gregkare** [remotestorage/website#25]

**Comment by rosano** [comment]
@raucao if this is taken care of in discourse maybe close in favour of #53 ?

**Comment by raucao** [comment]
The title here also says "Discourse", but I don't remember having to manually update any certs for that recently.

@gregkare Maybe this was already done, but not closed?

**Comment by raucao** [comment]
@gregkare Looks like you may have missed my question there?
