### ISSUE TITLE
"Quick start" shortcut in homepage

### ISSUE THREAD

**Issue by lduboeuf** [remotestorage/website#26]
Would be great i think for newcomers to have a "Quick start" shortcut in homepage that points to https://wiki.remotestorage.io/RemoteStorage.js:Beginners%27_Guide

**Comment by skddc** [comment]
Any idea/opinion on where/how exactly to add it?

**Comment by lduboeuf** [comment]
humm i would place a "getting started" below section "Unhosted Architecture" in home page that summarize initial steps to get started  as well as a link in top left navigation bar, before "Get storage".
 I would also rename "Develop" to "Documentation" and place "Spec" link within it.

**Comment by skddc** [comment]
Good idea. I think it should be 3-fold, for the various cases, all under "Get started":

1. ... with integrating remoteStorage into your JavaScript app using remoteStorage.js (the reference client library); maybe also another link to getting started with your own client (or none)
2. ... with using remoteStorage apps, i.e. set up your own storage server or get a hosted account (-> Get Storage)
3. ... with offering remoteStorage accounts to your users, i.e. integrating the server part or using/integrating with an existing server program

Or maybe it makes more sense to have it be for all kinds of developers (but not end users) and link to various interesting things in addition to the beginner's guide for the reference client lib.

**Comment by lduboeuf** [comment]
ah, i see, there is at least  3 use cases  that remotestorage.io should respond, maybe a simple top menu with "Get storage" ( for end user) and "Documentation" ( where we can find 'beginners guide', 'spec', example apps...)  would be sufficient ?
