### ISSUE TITLE
Update CleanTalk Mediawiki extension

### ISSUE THREAD

**Issue by skddc** [remotestorage/website#27]
CleanTalk is warning us about an outdated extension in their UI. We need to [update it](https://www.mediawiki.org/wiki/Extension:Antispam).

**Comment by gregkare** [comment]
@skddc The last release is from May 2016 (https://www.mediawiki.org/wiki/Extension:Antispam) and that's the one we already use. I don't see a warning, do you still see it?

**Comment by skddc** [comment]
I don't see it anymore. Oh well.
