### ISSUE TITLE
Still don't understand what this thing is

### ISSUE THREAD

**Issue by rugk** [remotestorage/website#32]
What I understand:
* The aims of this project (in general)
* This is a protocol used for web apps without server interaction (what you call https://unhosted.org/ apps)
* This is about data storage somehow
* The data is not stored on a server (?)
* You have some kind of email for "login", but it is no real mail

What I do not understand:
* How can I register for that mail? If I enter any mail, I do not get far…
* Where is the data really stored? I mean, if not locally, it must be on some kind of server in the web, so it must be somewhere, huh?

It may miss:
* some (easy) demo/tutorial, so I can see what to do
* some funky SVG or animated SVG/HTML or whatever showing a graphic of the technical things in real time (points flying around, you get that, yeah… like "How does it work?" at the bottom of https://matrix.org/ to name an example)

**Comment by rugk** [comment]
BTW your forums are broken. I wanted to post it there, but I still did not got the sign-up mail.

**Comment by skddc** [comment]
Thanks for opening this issue. It seems we need to improve the exlanations on the website.

> BTW your forums are broken. I wanted to post it there, but I still did not got the sign-up mail.

I just checked the mailserver logs, and there's only one signup attempt today. I won't post the email address for privacy reasons (although it seems to be a throwaway account). According to the logs it sent out the confirmation email, but that was marked as spam (perhaps automatically), so the second attempt failed with "Not delivering to a user who marked your messages as spam". It's using Mailgun to send the emails, which is usually rather solid. Perhaps you could check your spam folder, and potentially unmark it?

**Comment by skddc** [comment]
Let us know if you want to transfer the request to the forums, so it's easier for other newcomers to find it, or if you want someone to explain it here. I guess this would be the best place to put it: https://community.remotestorage.io/c/getting-started

**Comment by rugk** [comment]
Mail begins with `91`, no spam, just a redirect provider to anonymize your mail.

**Comment by skddc** [comment]
Yes, that's the one for which I described the mail server logs.

**Comment by rugk** [comment]
Never had any problem with them, do you support greylisting?

**Comment by skddc** [comment]
Could you confirm that your server and/or client didn't mark any of our emails as spam, please? I'm not an expert with email things, but that's what the logs show:

![rs-email-logs](https://user-images.githubusercontent.com/842/35093802-520b3614-fc3b-11e7-97b7-7e609767fbb8.png)

**Comment by rugk** [comment]
It's not my own server, but I see nothing marked as spam there. I can contract the provider company though…

**Comment by skddc** [comment]
That would be helpful, thanks!

**Comment by rugk** [comment]
> Let us know if you want to transfer the request to the forums,

I don't care. Do whatever you think would be the (more) appropriate place.

**Comment by skddc** [comment]
Well if you don't have a forums account, you cannot put it there and/or reply to anything. That's why I'm trying to solve the issue with the confirmation emails.

**Comment by rugk** [comment]
I've dropped them mail.

**Comment by rugk** [comment]
So they've replied and said they made changes to that thing. I triggered the mail again… let's see…

**Comment by thornjad** [comment]
@rugk did you get the confirmation email issue sorted out?

**Comment by rugk** [comment]
So tried to sign-up, still get no mail.

**Comment by skddc** [comment]
Could you please use a different email address? Our email provider is preventing us from sending to an address that previously reported our email as spam.

**Comment by skddc** [comment]
@thornjad Do you have trouble signing up? I don't see any recent delivery issues other than the one @rugk ran into again just today.

**Comment by thornjad** [comment]
No no, I haven't had any problems, I'm just out reviving stale issues
