### ISSUE TITLE
Add all topbar items to mobile topbar dropdown

### ISSUE THREAD

**Issue by raucao** [remotestorage/website#41]
At the moment, only the main links from the left side are shown, but not the additional ones from the right. I think they should all be part of the mobile view as well.

**Comment by raucao** [comment]
I was updating the links due to the wiki/website merge just now, and noticed that Discourse had introduced a desktop/mobile split for custom components at some point, and migrated all existing ones to be desktop-only. Thus, the topbar wasn't even visible at all on mobile anymore.

I have moved it to be common component code, and also changed it to show the secondary navbar links on mobile as well now.

**Comment by rosano** [comment]
I added a link to the library as well, I think we had mentioned it on a call and forgot.

**Comment by raucao** [comment]
I don't remember that. We have many libraries, so just saying "library" isn't very useful to be honest. This particular library is the reference JavaScript client.
