### ISSUE TITLE
Retire the wiki

### ISSUE THREAD

**Issue by raucao** [remotestorage/website#61]
Since we have moved all relevant wiki content to the new website in #59, we can now retire the wiki.

I have already re-configured the Discourse server to use Nginx on the host instead of the Discourse container, and added and tested a new wiki vhost to redirect certain pages to the new ones, and all others simply to the frontpage.

Only opening this to switch DNS, configure TLS with Let's Encrypt, and test again that everything works, and to have the removal of the wiki documented properly.

**Comment by raucao** [comment]
By the way, just in general, I think we should point people a bit more to the Discourse and explain that they can also create wiki topics there, which others can edit, too.

**Comment by rosano** [comment]
Thanks for setting up all of that. I agree there's a lot of potential in Discourse for collaborative writing and thinking. I had opted to avoid it for the website pages in favour of peer review, but for discussion and maybe moving away from GitHub, it's an excellent option. We can maybe set an example for how to do that for a given topic or issue.

**Comment by raucao** [comment]
All done. The wiki is no more. :boom:
