### ISSUE TITLE
Show contributors from commits

### ISSUE THREAD

**Issue by rosano** [remotestorage/website#62]
Seems like Jekyll [supports](https://jekyll.github.io/github-metadata/site.github) `contributors` to the current repository or `organization_members` which exclude people from commits. Ideally there would be something like `organization_contributors` to show people from commits in all repositories across an organization.

I found some ways to show this information via the GitHub API:
- https://daquinoaldo.github.io/organization-contributions/?org=remotestorage
-  https://api.github.com/orgs/remotestorage/repos
- https://api.github.com/repos/remotestorage/website/contributors

and will try to either integrate directly with our project, create a plugin, or PR to Jekyll. Will post updates here.

**Comment by raucao** [comment]
The new website shows all contributors from commits to relevant RS repos. The script still has to be run manually, and it will update a JSON file:

https://github.com/remotestorage/website/blob/master/scripts/fetch-contributors.mjs
