### ISSUE TITLE
Reformat apps.md from HTML to actual Markdown

### ISSUE THREAD

**Issue by DougReeder** [remotestorage/website#75]

**Comment by raucao** [comment]
Wouldn't it be nice if the data were actually stored in something like a YAML file, and the final page built from that? Shouldn't be too hard with Jekyll...

**Comment by silverbucket** [comment]
Is there a reason not to use Markdown as the source language over YAML? There are plenty of Markdown to X format tools available.

**Comment by raucao** [comment]
Not sure what you mean. I'm talking about the data only, not the source markup. Having to mess around with large table markup in Markdown is just very inconvenient and error-prone for adding an entry to a list. Also, it can auto-sort the data, so you can just add entries to the bottom of the list.

**Comment by raucao** [comment]
Not sure when, but the page has been converted to Markdown a while ago.
