### ISSUE TITLE
Add calls to action

### ISSUE THREAD

**Issue by raucao** [remotestorage/website#9]
The current version of the new site doesn't give any pointers for where to go next. Some things could also still be added to the frontpage (like "check out some apps" with a link to "browse more apps" etc.). I guess it's mostly just adding "learn more"-type links to the various sections.

**Comment by untitaker** [comment]
The actual calls for action should be part of the community section. Demo apps can be located at the very top. Sharesome would be a neat example. Perhaps we could include a demo video from somewhere?

**Comment by skddc** [comment]
> Perhaps we could include a demo video from somewhere?

That'd be great. I think we'd need to make a new one, though.
